In [1]:
import numpy as np

In [2]:
np.random.seed(0)
np.random.rand(5)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])

In [3]:
np.random.rand(10)

array([ 0.64589411,  0.43758721,  0.891773  ,  0.96366276,  0.38344152,
        0.79172504,  0.52889492,  0.56804456,  0.92559664,  0.07103606])

In [4]:
np.random.rand(10)

array([ 0.0871293 ,  0.0202184 ,  0.83261985,  0.77815675,  0.87001215,
        0.97861834,  0.79915856,  0.46147936,  0.78052918,  0.11827443])

In [5]:
np.random.seed(0)

In [6]:
np.random.rand(5)

array([ 0.5488135 ,  0.71518937,  0.60276338,  0.54488318,  0.4236548 ])

In [7]:
print np.random.rand(10)
print np.random.rand(10)

[ 0.64589411  0.43758721  0.891773    0.96366276  0.38344152  0.79172504
  0.52889492  0.56804456  0.92559664  0.07103606]
[ 0.0871293   0.0202184   0.83261985  0.77815675  0.87001215  0.97861834
  0.79915856  0.46147936  0.78052918  0.11827443]


In [8]:
x = np.arange(10)
print x
np.random.shuffle(x)
print x

[0 1 2 3 4 5 6 7 8 9]
[3 6 4 5 2 9 7 8 1 0]


In [9]:
np.random.choice(5, 5, replace=False)

array([1, 4, 0, 3, 2])

In [10]:
np.random.choice(5, 3, replace=False)

array([2, 1, 3])

In [11]:
np.random.choice(5, 10)

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [15]:
np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0])

array([2, 3, 3, 3, 0, 3, 3, 3, 3, 3])

In [16]:
np.random.rand(10)

array([ 0.05571469,  0.45115921,  0.01998767,  0.44171092,  0.97958673,
        0.35944446,  0.48089353,  0.68866118,  0.88047589,  0.91823547])

In [17]:
np.random.rand(3, 5)

array([[ 0.21682214,  0.56518887,  0.86510256,  0.50896896,  0.91672295],
       [ 0.92115761,  0.08311249,  0.27771856,  0.0093567 ,  0.84234208],
       [ 0.64717414,  0.84138612,  0.26473016,  0.39782075,  0.55282148]])

In [19]:
np.random.randn(10)

array([ 1.44073112, -1.14907568,  0.80571455,  1.75610703,  0.97297991,
       -1.55111911,  0.19114348,  1.60477607, -1.42002593, -2.44378268])

In [22]:
np.random.randn(3,5)

array([[-0.2524676 ,  1.03984679, -0.02347953,  0.08942229, -0.59432737],
       [-0.10569679,  0.74279571, -0.75498153, -0.13828271, -2.12492027],
       [-1.03001883, -0.51745186, -0.14180001, -1.27648021,  1.48151328]])

In [23]:
np.random.randint(10, size=10)

array([1, 0, 3, 8, 8, 4, 4, 0, 9, 3])

In [26]:
np.random.randint(10,20, size= 10)

array([19, 19, 12, 10, 19, 11, 19, 10, 16, 10])

In [27]:
np.random.randint(10, 20, size=(3,5))

array([[14, 18, 14, 13, 13],
       [18, 18, 17, 10, 13],
       [18, 17, 17, 11, 18]])

In [28]:
np.unique([11, 11, 2, 2, 34, 34])

array([ 2, 11, 34])

In [29]:
a = np.array(['a', 'b', 'b', 'c', 'a'])
index, count = np.unique(a, return_counts=True)

In [32]:
index

array(['a', 'b', 'c'], 
      dtype='|S1')

In [33]:
count

array([2, 2, 1])

In [31]:
np.unique([1, 3, 1, 2, 5, 2, 1], return_counts = True)

(array([1, 2, 3, 5]), array([3, 2, 1, 1]))

In [34]:
np.bincount([1, 1, 2, 2, 2, 3], minlength=6)

array([0, 2, 3, 1, 0, 0])

In [35]:
x = np.array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
                2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13,
                1,   0,  16,  15,   2,   4,  -7, -18,  -2,   2,  13,  13,  -2,
               -2,  -9, -13, -16,  20,  -4,  -3, -11,   8, -15,  -1,  -7,   4,
               -4, -10,   0,   5,   1,   4,  -5,  -2,  -5,  -2,  -7, -16,   2,
               -3, -15,   5,  -8,   1,   8,   2,  12, -11,   5,  -5,  -7,  -4])

In [36]:
len(x)

78

In [37]:
np.mean(x)

0.69230769230769229

In [38]:
np.var(x)

96.059171597633139

In [39]:
np.std(x)

9.8009780939268065

In [40]:
np.max(x)

23

In [41]:
np.min(x)

-24

In [42]:
np.median(x)

0.5

In [44]:
np.percentile(x, 25)

-5.75

In [45]:
np.percentile(x, 50)

0.5

In [46]:
np.percentile(x, 75)

5.0

In [50]:
from scipy import stats

In [52]:
stats.describe(x)

DescribeResult(nobs=78, minmax=(-24, 23), mean=0.69230769230769229, variance=97.306693306693305, skewness=0.11586487731702556, kurtosis=-0.15461828136911615)

In [56]:
import pandas as pd
s = pd.Series(x)
print s

0     18
1      5
2     10
3     23
4     19
5     -8
6     10
7      0
8      0
9      5
10     2
11    15
12     8
13     2
14     5
15     4
16    15
17    -1
18     4
19    -7
20   -24
21     7
22     9
23    -6
24    23
25   -13
26     1
27     0
28    16
29    15
      ..
48   -15
49    -1
50    -7
51     4
52    -4
53   -10
54     0
55     5
56     1
57     4
58    -5
59    -2
60    -5
61    -2
62    -7
63   -16
64     2
65    -3
66   -15
67     5
68    -8
69     1
70     8
71     2
72    12
73   -11
74     5
75    -5
76    -7
77    -4
dtype: int32


In [57]:
s.describe()

count    78.000000
mean      0.692308
std       9.864416
min     -24.000000
25%      -5.750000
50%       0.500000
75%       5.000000
max      23.000000
dtype: float64