In [61]:
import numpy as np
import scipy as sp
from scipy import stats

N = 10
theta_0 = 0.5
x = sp.stats.bernoulli(theta_0).rvs(N)
n = np.count_nonzero(x)
n

2

In [62]:
stats.binom_test(n, N)

0.10937500000000003

In [63]:
N = 100
theta_0 = 0.5
np.random.seed(0)
x = sp.stats.bernoulli(theta_0).rvs(N)
n = np.count_nonzero(x)
n

49

In [64]:
sp.stats.binom_test(n, N)

0.92041076261282062

In [65]:
N = 100
theta_0 = 0.35
np.random.seed(0)
x = sp.stats.bernoulli(theta_0).rvs(N)
n = np.count_nonzero(x)
n

31

In [66]:
sp.stats.binom_test(n, N)

0.00018314322488235352

In [67]:
N = 10
K = 4
theta_0 = np.ones(K)/K
np.random.seed(0)
x = np.random.choice(K, N, p=theta_0)
n = np.bincount(x, minlength=K)
n

array([0, 3, 5, 2])

In [68]:
sp.stats.chisquare(n)

Power_divergenceResult(statistic=5.1999999999999993, pvalue=0.157724450396663)

In [69]:
N = 100
K = 4
theta_0 = np.array([0.35, 0.30, 0.20, 0.15])
np.random.seed(0)
x = np.random.choice(K, N, p=theta_0)
n = np.bincount(x, minlength=K)
n

array([37, 32, 20, 11])

In [70]:
sp.stats.chisquare(n)

Power_divergenceResult(statistic=16.559999999999999, pvalue=0.00087034719789121269)

In [71]:
N = 10
mu_0 = 0
np.random.seed(0)
x = sp.stats.norm(mu_0).rvs(N)
x

array([ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
       -0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ])

In [82]:
len(x)

10

In [103]:
def ztest_1samp(x, sigma2=1, mu=0):
    print (x.mean() - mu)
    print np.sqrt(sigma2/float(len(x)))
    z = (x.mean() - mu)/ np.sqrt(sigma2/float(len(x)))
    return z, 2 * sp.stats.norm().sf(np.abs(z))

In [104]:
ztest_1samp(x)

0.738023170729
0.316227766017


(2.3338341854824276, 0.019604406021683538)

In [105]:
N = 100
mu_0 = 0
np.random.seed(0)
x = sp.stats.norm(mu_0).rvs(N)

In [106]:
ztest_1samp(x)

0.0598080155345
0.1


(0.59808015534484993, 0.54978645086241684)